name: Build workflow
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - run: |
          cd examples
          
          cd 09.Tools
          make
          cd ..
          
          cd ..
