name: Check workflow
 
on: [push]
 
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Build 09.Tools example
        working-directory: ./examples/09.Tools
        run: make
      - name: Build 12.Graph example
        working-directory: ./examples/12.Graph/igraph
        run: |
          echo sudo apt install libigraph-dev
          echo make
          echo Fails on Ubuntu, so not yet...
      - name: Кибердядька
        uses: dluciv/cyber-under-tutor@main
        with:
          whom-to-greet: 'Я родимый'
